name = "api"
type = "javascript"
zone_id = ""
account_id = "d0d0173df50c14f476b7575785e5b684"
route = "https://api.defiplaza.net/*"
workers_dev = true
compatibility_date = "2021-10-14"

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
