name = "api"
account_id = "d0d0173df50c14f476b7575785e5b684"
route = "https://api.defiplaza.net/*"
workers_dev = true
compatibility_date = "2021-10-14"
main = "dist/worker.js"

[triggers]
crons = ["* * * * *", "*/5 * * * *", "59 23 * * *"]

[build]
command = "npm run build"
